# Generated by Django 5.1.9 on 2025-05-27 13:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netcdf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[("ssp245", "SSP-245"), ("ssp585", "SSP-585")],
                        max_length=10,
                    ),
                ),
                (
                    "variable",
                    models.CharField(
                        choices=[("pr", "Precipitation"), ("tas", "Temperature")],
                        max_length=10,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("DJF", "DJF"),
                            ("MAM", "MAM"),
                            ("JJA", "JJA"),
                            ("SON", "SON"),
                            ("Annual", "Annual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period", models.CharField(max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("value", models.FloatField()),
                ("p_value", models.FloatField()),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scenario", "variable", "season", "period"],
                        name="netcdf_clim_scenari_f6c91e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FileCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("geotiff", "GeoTIFF"), ("geojson", "GeoJSON")],
                        max_length=10,
                    ),
                ),
                ("scenario", models.CharField(max_length=10)),
                ("variable", models.CharField(max_length=10)),
                ("season", models.CharField(max_length=10)),
                ("period", models.CharField(max_length=20)),
                ("file", models.FileField(upload_to="caches/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    ("file_type", "scenario", "variable", "season", "period")
                },
            },
        ),
    ]
