# Generated by Django 5.1.9 on 2025-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netcdf", "0002_climatedata_filecache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatedata",
            name="variable",
            field=models.CharField(
                choices=[
                    ("pr", "Precipitation"),
                    ("tas", "Temperature"),
                    ("tasmax", "Max Temperature"),
                    ("tasmin", "Min Temperature"),
                ],
                max_length=10,
            ),
        ),
    ]
